### ISSUE TITLE
混合开发，如何集成到Module里？

### ISSUE THREAD

**Issue by LeoAiolia** [easemob/im_flutter_sdk#160]
目前module文件引入依赖后：
```
im_flutter_sdk:
        git:
            url: https://github.com/easemob/im_flutter_sdk.git
            ref: dev
```
flutter attach没问题，但是`flutter build ios-framework`会报错

![图片](https://user-images.githubusercontent.com/16910025/92990038-4340ff80-f50b-11ea-8dad-33ca90ee244a.png)
