### ISSUE TITLE
能再pub上更新一下吗

### ISSUE THREAD

**Issue by tudosxxx** [easemob/im_flutter_sdk#260]
然后弄点例子，比如发送消息方法。发送图片方法。接收的方法

**Comment by dujiepeng** [comment]
@hx269988653  目前在demo中已经有实现，暂时还没有更新到pub.dev上，您可以通过
```
dependencies:
  im_flutter_sdk:  
    git:  
      url: https://github.com/easemob/im_flutter_sdk.git 
      ref: stable
```
方式集成，后续我们会安排更新到pub.dev上。
